### PR TITLE
repair command

### PR DESCRIPTION
**Pull request by 12944qwerty**
shortens 
```
npm run unplug
git pull
npm run plug
```
into `npm run repair`

### CODE REVIEW

**Review by asportnoy — APPROVED** [review]
Much better lol

**Review by D3XX3R — APPROVED** [review]
looks good

**Comment by D-Brox** [comment]
I would have called it `replug`

**Comment by asportnoy** [comment]
I think that would confuse people. `replug` sounds like either plug but for after you've already unplugged or some unknown branding term. Repair is more self-explanitory.

**Pull request merged**
