### PR TITLE
Improve ESLint config

### PR DESCRIPTION
**Pull request by lexisother**

### CODE REVIEW

**Review by lleyton — APPROVED** [review]

**Comment by Vendicated** [comment]
you should probably lint all files as well so lint passes again and you have a clean base to work with

**Comment by lexisother** [comment]
Unless @lleyton volunteers to fix all the new linting issues in this PR, they'll be fixed later. I genuinely don't care.

**Review by asportnoy — CHANGES_REQUESTED** [review]
If we're making changes to the lint config, we need to format everything like @Vendicated said. It's not like it's hard to do or anything, it's one command.

**Comment by lexisother** [comment]
...what? It sounds like you haven't ran `npm run lint` yourself.

**Comment by lleyton** [comment]
Honestly, not worth it for me to go and fix all of the linting issues; here's everything eslint was able to automatically fix though. Let's merge this regardless.

**Review by FifiTheBulldog — APPROVED** [review]

**Comment by Vendicated** [comment]
If you're not gonna lint, why even add such a strict config? Maybe it would make more sense to use a more lenient one for now and opt into the stricter rules later if necessary

**Comment by lexisother** [comment]
It literally doesn't matter. The current config sucks and that's all I care about changing. It's not even being followed right now because fixing linting issues isn't a priority for now. I'll go over the entire repo to fix things if it gets merged before I wake up tomorrow.

**Comment by lleyton** [comment]
I don't give a fuck.

**Comment by asportnoy** [comment]
bruh

**Pull request merged**
