### PR TITLE
Select component

### PR DESCRIPTION
**Pull request by FedeIlLeone**
Adds a `Select` component.

Example:
```tsx
<Select
  options={[
    { label: "Option 1", value: "opt1" },
    { label: "Option 2", value: "opt2" },
    { label: "Option 3", value: "opt3" },
  ]}
  onSelect={(e) => setSelected(e)}
  isSelected={(e) => e === selected}
  onClear={() => setSelected("")}
  clearable
  placeholder="Placeholder text"
/>
```

image

Closes: #368

### CODE REVIEW

**Review by asportnoy — CHANGES_REQUESTED** [review]
Let's add a wrapper similar to this so we can use more traditional `value` / `onChange` (and work with useSetting too)
Screenshot on 2023-02-02 at 17 57 41

**Comment by FedeIlLeone** [comment]
Ok done, I think thats what you meant.

**Review by asportnoy — CHANGES_REQUESTED** [review]
2 requests: Can we make the value type string only instead of string or number? And can you add a `SelectItem` wrapper like with radio? Looks good otherwise!

**Comment by FedeIlLeone** [comment]
Done
image

**Review by asportnoy — APPROVED** [review]
Thanks!

**Pull request merged**
