### PR TITLE
15 req/s ?

### LINKED ISSUE #524: Limit number of parallel update requests
The Replugged API has a rate limit of 20 requests per second. However, the updater currently requests all updates at once ([relevant code](https://github.com/replugged-org/replugged/blob/615fb152593a892d0e0b02a2e0fb0af39d738d17/src/renderer/managers/updater.ts#L221-L224)). The check should be throttled to 15 requests per second (give some wiggle room) and properly handle 429s.

In the future, we should add a route to the backend for a bulk update check to avoid needing a lot of requests like this.

### PR DESCRIPTION
**Pull request by TheHellTower**
Fixes #524

### CODE REVIEW

**Review by asportnoy — CHANGES_REQUESTED** [review]
This will only run 1 request at a time and delay between each one. We want to run as many as possible at a time until we hit 15 within a second, *then* delay it until it won't be over 15/s.

**Comment by TheHellTower** [comment]
Review please 😔

**Review by asportnoy — CHANGES_REQUESTED** [review]
This will still only request one at a time rather than doing them in parallel

**Comment by TheHellTower** [comment]
> This will still only request one at a time rather than doing them in parallel

Oh so you didn't mean in a row but really all of them at the "exact" same time

**Comment by asportnoy** [comment]
Yes, it should run as many as possible in parallel until it hits the limit and then throttle starting the next request until 1 second has passed since the first request.

**Pull request closed without merging**
