### PR TITLE
Quick CSS toggleable

### PR DESCRIPTION
**Pull request by thennothinghappened**
Added a switch on the Quick CSS menu to toggle it on or off!

[video](https://user-images.githubusercontent.com/35243139/183823649-314d3b4c-4b48-436f-b0f9-c305d949f310.mp4)

### CODE REVIEW

**Review by lleyton — CHANGES_REQUESTED** [review]
fix the lint errors, nya

**Comment by thennothinghappened** [comment]
> fix the lint errors, nya

working on it

**Comment by thennothinghappened** [comment]
has that worked?

**Comment by thennothinghappened** [comment]
should be fully working

**Review by lleyton — APPROVED** [review]

**Pull request merged**
