### PR TITLE
Fix FormText component

### PR DESCRIPTION
**Pull request by E-boi**
get the correct module for the FormText component

### CODE REVIEW

**Comment by asportnoy** [comment]
This doesn't seem to change anything on either Canary or Stable.

**Comment by E-boi** [comment]
hm weird when I made this pr it would get some other component which would cause the crash but now it doesn't

**Comment by asportnoy** [comment]
Gonna close this for now, we can revisit if the issue comes back.

**Comment by E-boi** [comment]
The issue is happening again

**Comment by asportnoy** [comment]
Still can't reproduce. Can you show the console output with and without this change? Also, what's your platform info?

**Comment by E-boi** [comment]
wdym console output? the error or something else?

**Comment by E-boi** [comment]
My platform info:
image

The error without this change:
image

Simplist code that i've been able to reproduce with (used for a setting page):
```js
import { components } from "replugged";
const { FormText } = components;

export default () => {
  return (
    <div>
      <FormText.DESCRIPTION>Hello world</FormText.DESCRIPTION>
    </div>
  );
};
```

**Comment by asportnoy** [comment]
Can you log the component in the console though? Just `replugged.components.FormText`

**Comment by E-boi** [comment]
The both are the same since FormText doesn't export the module itself

without the change:
image

with the change:
image

**Review by asportnoy — APPROVED** [review]
Still can't reproduce on stable or canary but I don't think this PR will hurt anything so I'll go ahead and approve

**Pull request merged**
