### PR TITLE
Implement plugin embeds

### PR DESCRIPTION
**Pull request by lexisother**
Does as it says on the tin. WIP!

### CODE REVIEW

**Comment by lexisother** [comment]
Feel free to merge this as an experiment. I will wait for the completion of the store to make this user-facing by default.

Unless you folks say "take the plunge". Your risk, though.

**Review by lleyton — APPROVED** [review]
disregarding the TODOs, seems legit

**Review by asportnoy — APPROVED** [review]

**Review by 12944qwerty — APPROVED** [review]
Delete embeds if poll asks for it. Otherwise approved

**Comment by asportnoy** [comment]
Merging this as a lab, we can add the embed hiding etc later

**Pull request merged**
