### PR TITLE
fix(main): Fix `electron-devtools-installer` & Watch Together

### PR DESCRIPTION
**Pull request by GriefMoDz**
... again

### CODE REVIEW

**Review by lexisother — CHANGES_REQUESTED** [review]
Not a real request for review, just blocking.

@CanadaHonk Please review.

**Comment by CanadaHonk** [comment]
Why is a custom CSP with `frame-ancestors` being set at all? It just limits what origins can be an iframe in the page, which I don't see any reason to do?

**Comment by GriefMoDz** [comment]
> Why is a custom CSP with `frame-ancestors` being set at all? It just limits what origins can be an iframe in the page, which I don't see any reason to do?

It actually does the opposite. By stripping the `x-frame-options` header and using `frame-ancestors` in its place, it opens up the use of embedded content.

As a result, plugins can now use embedded content (`iframe`s and other surrounding elements) on a majority of websites, as long as the request originates from within Discord's domain(s) - as specified under the `frame-ancestors` policy.

This is particularly useful for plugins that wish to embed a website such as "https://duckduckgo.com" that would previously fail due to it being blocked because it hasn't come from the same origin.

**Comment by CanadaHonk** [comment]
Oh lol I got it confused with `frame-src`. I agree, lgtm.

**Review by CanadaHonk — APPROVED** [review]

**Review by lexisother — APPROVED** [review]

**Pull request merged**
