### PR TITLE
make manifest checking updates only ff to the commit that updated manifest

### PR DESCRIPTION
**Pull request by Vap0r1ze**
yea

### CODE REVIEW

**Comment by Vap0r1ze** [comment]
problem: i think ui will not display the right commits

**Review by lleyton — CHANGES_REQUESTED** [review]
https://discord.com/channels/1000926524452647132/1000955965304221728/1013359653708644403

also, contributors are now required to take a sobriety test before submitting a PR

**Comment by Vap0r1ze** [comment]
> also, contributors are now required to take a sobriety test before submitting a PR

 i can fake a soberty test ..

**Comment by lleyton** [comment]
Looks good but can you:
1. Refractor some of the variable names to make it look like you're less high
2. Local validation

**Review by lleyton — APPROVED** [review]

**Pull request merged**
