### PR TITLE
Slash Commands

### LINKED ISSUE #230: Commands Coremod (switch to slash commands)

### LINKED ISSUE #232: Add Missing Coremods
- [x] #255
- [x] #249
- [x] #230 
- [x] #250
- [x] #251
- [x] #256
- [x] #252
- [x] #253
- [x] #231 
- [x] #239 
- [x] #254

### PR DESCRIPTION
**Pull request by 12944qwerty**
Closes #230 

Currently only has enable and disable addons. However, we can add more soon

Still needs some work on typing _better_ but otherwise it should be good.

### CODE REVIEW

**Comment by ShadiestGoat** [comment]
Hello, what is the status on this?

**Comment by Tharki-God** [comment]
Is this ever gonna be finished?

**Comment by Tharki-God** [comment]
Shouldn't this be closed now?

**Comment by asportnoy** [comment]
Closing in favor of #501

**Pull request closed without merging**
